/**
 * @file    config.c
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * Const configuration tables in PROGMEM; the pool arena is the
 * only RAM contributed here (user payload, reported separately
 * from the kernel RAM budget).
 */

#include <avr/pgmspace.h>

#include "eros.h"

const OsTaskConfigType OS_taskConfig[OS_NUM_TASKS] PROGMEM =
{
    [TASK_INIT] = { Task_Init, 1u /* autostart */, 2u /* WCET ticks */ },
    [TASK_KNOB] = { Task_knob, 0u /* autostart */, 2u /* WCET ticks */ },
};

const OsAlarmConfigType OS_alarmConfig[OS_NUM_ALARMS] PROGMEM =
{
    [ALARM_KNOB] = { TASK_KNOB },
};

const OsResourceConfigType OS_resourceConfig[OS_NUM_RESOURCES] PROGMEM =
{
    [RES_RTE] = { TASK_KNOB /* ceiling */, 0u /* mask tick ISR */ },
};

uint8_t OS_poolArena[(uint16_t)OS_POOL_NUM_BLOCKS * OS_POOL_BLOCK_SIZE];
