/**
 * @file    knob_Intfc.h
 * @brief   Hand-authored ASW ports for 'knob' (the RTE reads inputs / writes outputs here).
 *
 * GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 */

#ifndef KNOB_INTFC_H
#define KNOB_INTFC_H

#include <stdint.h>

/* Input ports */
extern uint16_t IN_KnbVal;   /* knob ADC reading */

/* Output ports */
extern uint8_t OUT_Led;   /* status LED */

#endif /* KNOB_INTFC_H */
