/**
 * @file    knob_Param.c
 * @brief   Calibration values for 'knob' (edit values in app.yaml).
 *
 * GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 */

#include "knob_Param.h"

uint16_t Knb_Thresh = 512;   /* on/off threshold */
