/**
 * @file    knob.h
 * @brief   Entry points for the 'knob' ASW task.
 *
 * GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 */

#ifndef KNOB_H
#define KNOB_H

void knob_initialize(void);
void knob_Runnable(void);

#endif /* KNOB_H */
