/**
 * @file    knob_Param.h
 * @brief   Tunable calibrations for 'knob'.
 *
 * GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 */

#ifndef KNOB_PARAM_H
#define KNOB_PARAM_H

#include <stdint.h>

extern uint16_t Knb_Thresh;   /* on/off threshold */

#endif /* KNOB_PARAM_H */
