/**
 * @file    knob_Intfc.c
 * @brief   Storage for 'knob' ASW ports.
 *
 * GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 */

#include "knob_Intfc.h"

uint16_t IN_KnbVal;   /* knob ADC reading */
uint8_t OUT_Led;   /* status LED */
