/**
 * @file    os_gen.h
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * Regenerated on every erosgen run - never edit. Include it
 * from main.c and call Board_ConfigurePins() in StartupHook()
 * and OS_StartAlarms() in the autostart task, so pin and alarm
 * wiring stay in sync with the YAML.
 */

#ifndef OS_GEN_H
#define OS_GEN_H

#include <avr/io.h>
#include "eros.h"

/** Pin directions/pull-ups + enabled-driver init. Call from
 *  StartupHook() (interrupts still disabled). */
static inline void Board_ConfigurePins(void)
{
    /* no gpio or auto-init drivers configured */
}

/** Arm every cyclic alarm with ALIGNED releases (all first
 *  expiries at the base period so shared release points
 *  coincide). Call from the autostart task. */
static inline void OS_StartAlarms(void)
{
    (void)SetRelAlarm(ALARM_KNOB, 10u, TASK_KNOB_PERIOD_TICKS);
}

#endif /* OS_GEN_H */
