/**
 * @file    Rte.c
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * RTE implementation for the 'knob' model<->OS integration:
 * port adapters (IoHwAb) + lifecycle. Touches the ASW only through
 * its exported interface globals and the BSW through driver APIs.
 */

#include <avr/io.h>

#include "Rte.h"
#include "Rte_Cfg.h"

/* ASW - generated model (read-only) */
#include "knob.h"
#include "knob_Intfc.h"

/* BSW - MCAL drivers (read-only) */
#include "adc.h"

/* OS: the runnable is wrapped as an EROS task (Task_<model>). */
#include "eros.h"
#include "config.h"

/* --- Port adapters (IoHwAb): BSW signals <-> ASW ports ---------- */

static uint16_t Rte_Read_KnbVal(void)
{
    return Adc_ReadChannel(RTE_CFG_KNBVAL_ADC_CH);
}

static void Rte_Write_Led(uint8_t on)
{
    if (on)
    {
        RTE_CFG_LED_PORT |= (uint8_t)(1u << RTE_CFG_LED_BIT);
    }
    else
    {
        RTE_CFG_LED_PORT &= (uint8_t)~(1u << RTE_CFG_LED_BIT);
    }
}

/* --- Lifecycle ------------------------------------------------- */

void Rte_Init(void)
{
    /* BSW init for the bound ports. */
    Adc_Init();
    RTE_CFG_LED_DDR  |= (uint8_t)(1u << RTE_CFG_LED_BIT);
    RTE_CFG_LED_PORT &= (uint8_t)~(1u << RTE_CFG_LED_BIT);

    /* ASW init. */
    RTE_CFG_INIT_FN();
}

void Rte_Run_knob(void)
{
    /* implicit read: sensor ports <- BSW */
    RTE_CFG_KNBVAL_SIGNAL = Rte_Read_KnbVal();

    /* run the ASW runnable */
    RTE_CFG_RUNNABLE_FN();

    /* implicit write: actuator ports -> BSW */
    Rte_Write_Led(RTE_CFG_LED_SIGNAL);
}

/* --- OS task body: the cyclic alarm (armed by os_gen.h) ---------- */
/* activates this task; it runs one pass and terminates. --------- */

void Task_knob(void)
{
    Rte_Run_knob();
    TerminateTask();
}
