/**
 * @file    Rte_Cfg.h
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * Declarative ASW<->BSW binding for the 'knob' SWC: which
 * driver feeds each input port, which each output port actuates,
 * and the runnable rate. Pure configuration, no logic.
 */

#ifndef RTE_CFG_H
#define RTE_CFG_H

/* ---- SWC identity (ASW entry points) ---------------------------- */
#define RTE_CFG_INIT_FN            knob_initialize
#define RTE_CFG_RUNNABLE_FN        knob_Runnable

/* ---- Input ports: BSW sensor -> ASW port ------------------------ */
/* IN_KnbVal (uint16_T) <- adc */
#define RTE_CFG_KNBVAL_SIGNAL      IN_KnbVal
#define RTE_CFG_KNBVAL_ADC_CH      0u

/* ---- Output ports: ASW port -> BSW actuator --------------------- */
/* OUT_Led (boolean_T) -> dio */
#define RTE_CFG_LED_SIGNAL         OUT_Led
#define RTE_CFG_LED_DDR            DDRB
#define RTE_CFG_LED_PORT           PORTB
#define RTE_CFG_LED_BIT            5u

/* ---- Scheduling: runnable rate assigned to the OS -------------- */
#define RTE_CFG_PERIOD_MS          10u

#endif /* RTE_CFG_H */
