/**
 * @file    Rte_knob.h
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * Contract-phase application header for the 'knob' SWC: its RTE
 * run entry + the ports it binds. Include this alone to compile the
 * SWC's integration before the full system Rte.h is configured.
 */

#ifndef RTE_KNOB_H
#define RTE_KNOB_H

/* Input ports (BSW sensor / producer SWC -> ASW): */
/*   IN_KnbVal (uint16_T) <- adc */
/* Output ports (ASW -> BSW actuator): */
/*   OUT_Led (boolean_T) -> dio */

/** One activation of this SWC: read inputs -> run -> write outputs. */
void Rte_Run_knob(void);

#endif /* RTE_KNOB_H */
