# =====================================================================
# GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
#
# Application 'eros' on the EROS kernel. Only the peripherals
# selected in the YAML are compiled; everything else costs 0 bytes.
# =====================================================================

MCU     := atmega328p
F_CPU   := 16000000UL
TARGET  := eros

VPATH   := kernel

APP_SRCS := main.c actuator.c asw_10ms.c asw_50ms.c asw_500ms.c
SRCS     := $(APP_SRCS) eros.c config.c
OBJS     := $(SRCS:.c=.o)
DEPS     := $(SRCS:.c=.d)

CC      := avr-gcc
OBJCOPY := avr-objcopy
SIZE    := avr-size
AVRDUDE := avrdude

PORT    ?= /dev/ttyUSB0
BAUD    ?= 57600          # old-bootloader Nano; Optiboot: 115200

CFLAGS  := -Wall -Wextra -Werror -std=c99 -Os -flto \
           -ffunction-sections -fdata-sections -fno-common \
           -mmcu=$(MCU) -DF_CPU=$(F_CPU) \
           -I. -Ikernel
LDFLAGS := -Wl,--gc-sections -Wl,-Map=$(TARGET).map

BUDGET_DIR    := build_budget
CFLAGS_NOLTO  := $(filter-out -flto,$(CFLAGS))
FLASH_BUDGET  := 3072
RAM_BUDGET    := 128
SRAM_TOTAL    := 2048

.PHONY: all size budget flash clean config

all: $(TARGET).hex size budget

$(TARGET).elf: $(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

$(TARGET).hex: $(TARGET).elf
	$(OBJCOPY) -O ihex -R .eeprom $< $@

%.o: %.c
	$(CC) $(CFLAGS) -MMD -MP -c -o $@ $<

size: $(TARGET).elf
	@echo "---- final image (LTO) --------------------------------------"
	@$(SIZE) -B $(TARGET).elf

$(BUDGET_DIR):
	mkdir -p $(BUDGET_DIR)

$(BUDGET_DIR)/%.o: %.c | $(BUDGET_DIR)
	$(CC) $(CFLAGS_NOLTO) -MMD -MP -c -o $@ $<

APP_BUDGET_OBJS := $(addprefix $(BUDGET_DIR)/,$(APP_SRCS:.c=.o))

budget: $(BUDGET_DIR)/eros.o $(BUDGET_DIR)/config.o $(APP_BUDGET_OBJS)
	@echo "---- kernel budget check (non-LTO reference build) ----------"
	@$(SIZE) -B $(BUDGET_DIR)/eros.o $(BUDGET_DIR)/config.o \
	         $(APP_BUDGET_OBJS) | awk ' \
	  NR==2 { kflash += $$1 + $$2; kram   = $$2 + $$3 } \
	  NR==3 { kflash += $$1 + $$2; arena  = $$2 + $$3 } \
	  NR>=4 { appram += $$2 + $$3 } \
	  END { \
	    printf("kernel Flash (eros.o+config.o) : %4d / %d bytes\n", \
	           kflash, $(FLASH_BUDGET)); \
	    printf("kernel static RAM (eros.o)     : %4d / %d bytes\n", \
	           kram, $(RAM_BUDGET)); \
	    printf("pool arena (config.o, excluded)   : %4d bytes\n", arena); \
	    printf("application RAM (app objects)     : %4d bytes\n", appram); \
	    printf("stack + idle RAM (of %d total)  : %4d bytes\n", \
	           $(SRAM_TOTAL), $(SRAM_TOTAL) - kram - arena - appram); \
	    if (kflash > $(FLASH_BUDGET) || kram > $(RAM_BUDGET)) { \
	      printf("BUDGET EXCEEDED\n"); exit 1; \
	    } else { \
	      printf("budgets OK\n"); \
	    } \
	  }'

flash: $(TARGET).hex
	$(AVRDUDE) -v -p m328p -c arduino -P $(PORT) -b $(BAUD) \
	           -U flash:w:$(TARGET).hex:i

# Regenerate config.h/config.c/Makefile/os_gen.h from the YAML.
# Run this after editing app.yaml (config is NOT auto-rebuilt,
# so a Python-less CI can still 'make' from committed output).
config:
	python3 tools/erosgen.py app.yaml

clean:
	rm -rf $(OBJS) $(DEPS) $(BUDGET_DIR) \
	       $(TARGET).elf $(TARGET).hex $(TARGET).map

-include $(DEPS)
-include $(addprefix $(BUDGET_DIR)/,$(DEPS))
