"""Emitters for the "once" skeletons: per-rate asw_<n>ms.c and main.c.

These carry paired ``/* USER CODE BEGIN/END <id> */`` markers (see merge.py).
On regeneration cli.write refreshes the scaffold and re-injects the bytes inside
each marker, so a hand-edited ASW/main is preserved by id, not frozen wholesale.
A legacy skeleton with no markers is still kept untouched.
"""

from ..constants import INCLUDE_EROS_H
from ..merge import begin, end


def emit_asw_skeleton(s, task):
    step_call = None
    if s.simulink:
        for step, tname in (s.simulink.get("rate_map") or {}).items():
            if str(tname).upper() == task.name:
                step_call = f"{s.simulink['model']}_{step}();"
    tid = f"TASK_{task.name}"
    L = []
    L.append("/**")
    L.append(f" * @file    asw_{task.period_ms}ms.c")
    L.append(f" * @brief   {task.period_ms} ms rate - TASK_{task.name}.")
    L.append(" *")
    L.append(" * Generated by tools/erosgen.py. The scaffold (includes, task")
    L.append(" * signature, TerminateTask) is refreshed on every run; code inside")
    L.append(" * the USER CODE markers is preserved across regeneration. Keep")
    L.append(" * rate-local state static in this file; cross-rate signals belong")
    L.append(" * in an asw_signals module.")
    L.append(" */")
    L.append("")
    L.append(INCLUDE_EROS_H)
    if s.simulink:
        L.append(f'#include "{s.simulink["model"]}.h"')
    L.append(begin("INCLUDES"))
    L.append(end("INCLUDES"))
    L.append("")
    if task.runnables:
        L.append("/* Runnables you implement (here or in another TU). Move")
        L.append(" * these prototypes to a shared header if reused. */")
        for r in task.runnables:
            L.append(f"extern void {r}(void);")
        L.append("")
    L.append("/* File-scope rate-local state. */")
    L.append(begin(f"{tid}_STATE"))
    L.append(end(f"{tid}_STATE"))
    L.append("")
    L.append(f"/** TASK_{task.name} - {task.period_ms} ms, WCET <= "
             f"{task.wcet_ticks} tick(s). */")
    L.append(f"void {task.entry}(void)")
    L.append("{")
    L.append(f"    {begin(f'{tid}_BODY')}")
    if step_call:
        L.append("    /* sample: hardware -> model inports here */")
        L.append(f"    {step_call}")
        L.append("    /* actuate: model outports -> hardware here */")
    for r in task.runnables:
        L.append(f"    {r}();")
    if not step_call and not task.runnables:
        L.append("    /* TODO: runnables for this rate */")
    L.append(f"    {end(f'{tid}_BODY')}")
    L.append("    TerminateTask();")
    L.append("}")
    return "\n".join(L) + "\n"


def emit_main_skeleton(s):
    init = next((t for t in s.tasks if t.autostart), None)
    L = []
    L.append("/**")
    L.append(" * @file    main.c")
    L.append(" * @brief   Integration layer: hooks + init task + main().")
    L.append(" *")
    L.append(" * Generated by tools/erosgen.py. The scaffold is refreshed on every")
    L.append(" * run; code inside the USER CODE markers is preserved across")
    L.append(" * regeneration. Pin setup and alarm arming live in os_gen.h.")
    L.append(" */")
    L.append("")
    L.append(INCLUDE_EROS_H)
    L.append('#include "os_gen.h"')
    L.append(begin("INCLUDES"))
    L.append(end("INCLUDES"))
    L.append("")
    if s.hook_startup:
        L.append("void StartupHook(void)")
        L.append("{")
        L.append("    Board_ConfigurePins(); /* generated: gpio + driver init */")
        L.append(f"    {begin('STARTUP_HOOK')}")
        L.append(f"    {end('STARTUP_HOOK')}")
        L.append("}")
        L.append("")
    if s.hook_error:
        L.append("void ErrorHook(StatusType error)")
        L.append("{")
        L.append("    (void)error; /* may run in tick-ISR context: stay tiny */")
        L.append(f"    {begin('ERROR_HOOK')}")
        L.append(f"    {end('ERROR_HOOK')}")
        L.append("}")
        L.append("")
    if s.hook_shutdown:
        L.append("void ShutdownHook(StatusType error)")
        L.append("{")
        L.append("    (void)error; /* terminal fault tombstone */")
        L.append(f"    {begin('SHUTDOWN_HOOK')}")
        L.append(f"    {end('SHUTDOWN_HOOK')}")
        L.append("}")
        L.append("")
    if init is not None:
        L.append(f"/** TASK_{init.name} - autostart: arm the cyclic alarms. */")
        L.append(f"void {init.entry}(void)")
        L.append("{")
        if s.simulink:
            L.append(f"    {s.simulink['model']}_initialize();")
        L.append("    OS_StartAlarms(); /* generated from the YAML task set */")
        L.append(f"    {begin(f'TASK_{init.name}_BODY')}")
        L.append(f"    {end(f'TASK_{init.name}_BODY')}")
        L.append("    TerminateTask();")
        L.append("}")
        L.append("")
    L.append("int main(void)")
    L.append("{")
    L.append("    StartOS(); /* noreturn */")
    L.append("}")
    return "\n".join(L) + "\n"
