/**
 * @file    config.c
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * Const configuration tables in PROGMEM; the pool arena is the
 * only RAM contributed here (user payload, reported separately
 * from the kernel RAM budget).
 */

#include <avr/pgmspace.h>

#include "eros.h"

const OsTaskConfigType OS_taskConfig[OS_NUM_TASKS] PROGMEM =
{
    [TASK_STARTUP] = { Task_Startup, 1u /* autostart */, 2u /* WCET ticks */ },
    [TASK_STATUS] = { Task_Status, 0u /* autostart */, 2u /* WCET ticks */ },
    [TASK_RAMP] = { Task_Ramp, 0u /* autostart */, 1u /* WCET ticks */ },
    [TASK_CMD] = { Task_Cmd, 0u /* autostart */, 2u /* WCET ticks */ },
    [TASK_BUTTON] = { Task_Button, 0u /* autostart */, 1u /* WCET ticks */ },
};

const OsAlarmConfigType OS_alarmConfig[OS_NUM_ALARMS] PROGMEM =
{
    [ALARM_BUTTON] = { TASK_BUTTON },
    [ALARM_CMD] = { TASK_CMD },
    [ALARM_RAMP] = { TASK_RAMP },
    [ALARM_STATUS] = { TASK_STATUS },
};

const OsResourceConfigType OS_resourceConfig[OS_NUM_RESOURCES] PROGMEM =
{
    [RES_UART] = { TASK_CMD /* ceiling */, 0u /* mask tick ISR */ },
};

uint8_t OS_poolArena[(uint16_t)OS_POOL_NUM_BLOCKS * OS_POOL_BLOCK_SIZE];
