/**
 * @file    config.c
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * Const configuration tables in PROGMEM; the pool arena is the
 * only RAM contributed here (user payload, reported separately
 * from the kernel RAM budget).
 */

#include <avr/pgmspace.h>

#include "eros.h"

const OsTaskConfigType OS_taskConfig[OS_NUM_TASKS] PROGMEM =
{
    [TASK_INIT] = { Task_Init, 1u /* autostart */, 2u /* WCET ticks */ },
    [TASK_REPORT] = { Task_Report, 0u /* autostart */, 1u /* WCET ticks */ },
    [TASK_SLOW] = { Task_Slow, 0u /* autostart */, 1u /* WCET ticks */ },
    [TASK_MED] = { Task_Med, 0u /* autostart */, 1u /* WCET ticks */ },
    [TASK_FAST] = { Task_Fast, 0u /* autostart */, 1u /* WCET ticks */ },
};

const OsAlarmConfigType OS_alarmConfig[OS_NUM_ALARMS] PROGMEM =
{
    [ALARM_FAST] = { TASK_FAST },
    [ALARM_MED] = { TASK_MED },
    [ALARM_SLOW] = { TASK_SLOW },
};

const OsResourceConfigType OS_resourceConfig[OS_NUM_RESOURCES] PROGMEM =
{
    [RES_DEMO] = { TASK_FAST /* ceiling */, 1u /* mask tick ISR */ },
};

uint8_t OS_poolArena[(uint16_t)OS_POOL_NUM_BLOCKS * OS_POOL_BLOCK_SIZE];
