"""Shared literal constants: values emitted into generated files, plus a few
engine defaults shared across the generator, the report, and the GUI budget so
they can never drift apart.

GENERATED_BANNER deliberately names ``tools/erosgen.py`` (the shim entrypoint),
not the module doing the emitting - keep it stable so generated output is
byte-identical across the package refactor.
"""

__version__ = "0.1.0"                  # keep in sync with pyproject.toml

GENERATED_BANNER = "GENERATED by tools/erosgen.py from {src} - DO NOT EDIT"

MAIN_C = "main.c"                      # default application entry source
INCLUDE_EROS_H = '#include "eros.h"'   # kernel API include emitted in headers

# ---- Engine budget defaults -----------------------------------------------
# Single source of truth for numbers that three places used to hard-code
# independently (the Makefile's -DUART_*_SIZE, the report's RAM plan, and the
# GUI budget). Changing a value here updates all of them at once.
KERNEL_STATE_BYTES = 35                # fixed kernel bookkeeping RAM (est.)
UART_TX_RING_DEFAULT = 128             # default UART TX ring size (bytes)
UART_RX_RING_DEFAULT = 64              # default UART RX ring size (bytes)
