"""Shared literal constants emitted into generated files.

GENERATED_BANNER deliberately names ``tools/erosgen.py`` (the shim entrypoint),
not the module doing the emitting - keep it stable so generated output is
byte-identical across the package refactor.
"""

GENERATED_BANNER = "GENERATED by tools/erosgen.py from {src} - DO NOT EDIT"

MAIN_C = "main.c"                      # default application entry source
INCLUDE_EROS_H = '#include "eros.h"'   # kernel API include emitted in headers
