#!/usr/bin/env python3
"""erosgen - EROS system configurator (the "OIL file" compiler).

Reads one app.yaml per application and generates the static OS
configuration (config.h / config.c), the application Makefile, and -
for files that do not exist yet - per-rate ASW skeletons and a main.c
integration skeleton. Only peripherals listed in the YAML are compiled
in; buffer geometry (UART rings, pool arena) is set from the YAML so
RAM is spent deliberately.

Usage:
    python3 tools/erosgen.py <app.yaml> [--check]

    --check   validate + report only, write nothing

Design rules encoded here (see README.md / codegen/README.md):
  * TaskID == static priority == ready-mask bit; max 8 tasks.
  * Priorities are assigned rate-monotonically: fastest period =
    highest priority; aperiodic (activated/chained) tasks sit below
    the periodic set; the autostart init task is lowest.
  * One cyclic alarm per periodic task, IDs ordered fastest first.
  * Resource ceiling = highest-priority user (computed, not typed).
  * Schedulability gate: sum of all periodic WCETs must fit in the
    base (fastest) period - blocking, never corruption, but enforced.
"""

import difflib
import math
import os
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("erosgen: PyYAML required (pip install pyyaml)")

GENERATED_BANNER = "GENERATED by tools/erosgen.py from {src} - DO NOT EDIT"

# Driver name -> source file. Resolution order: application directory
# first (app-local driver like the demo's uart.c), then drivers_dir.
KNOWN_PERIPHERALS = {
    "uart":       "uart.c",
    "pwm":        "pwm.c",        # Timer1 PWM
    "adc":        "adc.c",
    "eeprom":     "eeprom.c",
    "i2c":        "i2c.c",
    "spi":        "spi.c",
    "extint":     "extint.c",
    "timer0_pwm": "timer0_pwm.c",
    "icp":        "icp.c",
    "acomp":      "acomp.c",
}

# Pins each peripheral drives when enabled - the single source of truth
# for conflict detection (replaces hardcoded peripheral-pair lists).
# Timer2 is the kernel tick and owns no application pins. ADC channels
# A0..A5 are only claimed if the app lists them (see peripheral config),
# so plain ADC declares nothing here.
PERIPHERAL_PINS = {
    "uart":       ["PD0", "PD1"],          # RXD, TXD
    "pwm":        ["PB1"],                 # OC1A
    "i2c":        ["PC4", "PC5"],          # SDA, SCL
    "spi":        ["PB2", "PB3", "PB4", "PB5"],  # SS, MOSI, MISO, SCK
    "timer0_pwm": ["PD5", "PD6"],          # OC0B, OC0A
    "icp":        ["PB0"],                 # ICP1
    "acomp":      ["PD7"],                 # AIN1 (AIN0/PD6 added if external)
    "extint":     [],                      # pins are app-assigned
    "eeprom":     [],
    "adc":        [],
}

# Shared-resource conflicts that are not expressible as pin overlap
# (two peripherals contending for the same timer/hardware block).
CONFLICTS_HARD = [
    ("icp", "pwm", "both own Timer1 (capture vs ICR1-as-TOP)"),
]

# Recognised keys per YAML section - anything else is a typo and is
# rejected (with a "did you mean" hint). This is the highest-value
# guard: a misspelled 'period_ms' would otherwise silently make a task
# aperiodic with no error.
ALLOWED_KEYS = {
    "doc":        {"system", "sources", "peripherals", "tasks",
                   "resources", "pool", "gpio", "simulink"},
    "system":     {"name", "kernel_dir", "drivers_dir", "tick_hz",
                   "alarm_max_offset", "stack", "hooks", "budget"},
    "stack":      {"canary", "guard_bytes", "paint_margin"},
    "hooks":      {"startup", "error", "shutdown"},
    "budget":     {"flash", "ram", "sram_total"},
    "task":       {"name", "entry", "period_ms", "wcet_ms", "autostart",
                   "watchdog", "runnables"},
    "resource":   {"name", "users", "mask_tick_isr"},
    "pool":       {"block_size", "blocks"},
    "gpio":       {"pin", "dir", "pullup", "name", "init"},
    "simulink":   {"model", "dir", "rate_map"},
    "uart":       {"baud", "tx_ring", "rx_ring"},
}


class ConfigError(Exception):
    pass


def fail(msg):
    raise ConfigError("erosgen: " + msg)


def check_keys(d, section, where):
    """Reject unknown keys in a YAML mapping, suggesting the closest
    valid key. `section` selects the allowed-key set; `where` names the
    location for the error message."""
    if not isinstance(d, dict):
        fail(f"{where}: expected a mapping, got {type(d).__name__}")
    allowed = ALLOWED_KEYS[section]
    for k in d:
        if k not in allowed:
            hint = difflib.get_close_matches(str(k), allowed, n=1)
            suffix = f" (did you mean '{hint[0]}'?)" if hint else \
                     f" (valid: {', '.join(sorted(allowed))})"
            fail(f"{where}: unknown key '{k}'{suffix}")


def is_pow2(n):
    return n >= 1 and (n & (n - 1)) == 0


# Arduino Nano silk -> ATmega328P port pin. Accept either form in YAML.
NANO_ALIASES = {}
for _d, _pp in {0: "PD0", 1: "PD1", 2: "PD2", 3: "PD3", 4: "PD4",
                5: "PD5", 6: "PD6", 7: "PD7", 8: "PB0", 9: "PB1",
                10: "PB2", 11: "PB3", 12: "PB4", 13: "PB5"}.items():
    NANO_ALIASES[f"D{_d}"] = _pp
for _a in range(6):  # A0..A5 double as PC0..PC5; A6/A7 are ADC-only
    NANO_ALIASES[f"A{_a}"] = f"PC{_a}"


def normalize_pin(name):
    """Return a canonical PORTxBIT pin name (e.g. 'PB5') from either an
    AVR name or an Arduino Nano alias ('D13', 'A4')."""
    p = str(name).upper()
    if p in NANO_ALIASES:
        return NANO_ALIASES[p]
    if (len(p) == 3 and p[0] == "P" and p[1] in "BCD" and p[2].isdigit()):
        return p
    fail(f"unknown pin '{name}' (use PB0..PD7 or Nano D0..D13 / A0..A5)")


# ---------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------

class Task:
    def __init__(self, d):
        if "name" not in d:
            fail("every task needs a name")
        self.name = str(d["name"]).upper()
        check_keys(d, "task", f"task '{self.name}'")
        self.entry = d.get("entry", "Task_" + self.name.capitalize())
        self.period_ms = d.get("period_ms")     # None = aperiodic
        self.wcet_ms = d.get("wcet_ms", 1)
        self.autostart = bool(d.get("autostart", False))
        self.watchdog = bool(d.get("watchdog", self.period_ms is not None))
        self.runnables = d.get("runnables", [])
        self.priority = None                    # assigned later
        self.period_ticks = None                # computed once tick known
        self.wcet_ticks = None
        if self.period_ms is not None and self.autostart:
            fail(f"task {self.name}: autostart tasks must be aperiodic "
                 "(they arm the alarms)")
        if self.watchdog and self.period_ms is None:
            fail(f"task {self.name}: watchdog supervision requires a period")

    def compute_ticks(self, tick_ms):
        if self.period_ms is not None:
            self.period_ticks = self.period_ms // tick_ms
        # WCET rounds UP to whole ticks (never under-budget), min 1.
        self.wcet_ticks = max(1, math.ceil(self.wcet_ms / tick_ms))


class Resource:
    def __init__(self, d, tasks_by_name):
        if "name" not in d:
            fail("every resource needs a name")
        check_keys(d, "resource", f"resource '{d['name']}'")
        self.name = str(d["name"]).upper()
        users = d.get("users", [])
        if not users:
            fail(f"resource {self.name}: needs a non-empty users list")
        self.users = []
        for u in users:
            key = str(u).upper()
            if key not in tasks_by_name:
                fail(f"resource {self.name}: unknown user task '{u}'")
            self.users.append(tasks_by_name[key])
        self.mask_tick_isr = bool(d.get("mask_tick_isr", False))

    @property
    def ceiling(self):
        return max(self.users, key=lambda t: t.priority)


class System:
    def __init__(self, doc, src_path):
        self.src = src_path
        if not isinstance(doc, dict):
            fail("top level of the YAML must be a mapping")
        check_keys(doc, "doc", "top level")
        sysd = doc.get("system", {})
        check_keys(sysd, "system", "system")
        self.name = sysd.get("name", "app")
        self.kernel_dir = sysd.get("kernel_dir", "../kernel")
        self.drivers_dir = sysd.get("drivers_dir")
        # The kernel's Timer2 tick is hardware-fixed at 1 kHz (register
        # values in eros.c are derived for 16 MHz / 1 kHz), so 1 tick ==
        # 1 ms is a kernel invariant, not a knob. Reject anything else
        # rather than silently emitting wrong alarm periods.
        self.tick_hz = int(sysd.get("tick_hz", 1000))
        if self.tick_hz != 1000:
            fail("tick_hz must be 1000: the EROS kernel tick (Timer2) is "
                 "fixed at 1 kHz; change the kernel to alter it")
        self.tick_ms = 1000 // self.tick_hz
        self.alarm_max_offset = int(sysd.get("alarm_max_offset", 32767))

        stack = sysd.get("stack", {})
        check_keys(stack, "stack", "system.stack")
        self.stack_canary = int(stack.get("canary", 0xC5))
        self.stack_guard = int(stack.get("guard_bytes", 8))
        self.stack_margin = int(stack.get("paint_margin", 16))

        hooks = sysd.get("hooks", {})
        check_keys(hooks, "hooks", "system.hooks")
        self.hook_startup = int(bool(hooks.get("startup", True)))
        self.hook_error = int(bool(hooks.get("error", True)))
        self.hook_shutdown = int(bool(hooks.get("shutdown", True)))

        self.budget = sysd.get("budget")  # dict or None
        if self.budget is not None:
            check_keys(self.budget, "budget", "system.budget")

        self.warnings = []

        # ---- tasks ----------------------------------------------------
        tasks = [Task(t) for t in doc.get("tasks", [])]
        if not 1 <= len(tasks) <= 8:
            fail("1..8 tasks required (8-bit ready mask)")
        names = [t.name for t in tasks]
        if len(set(names)) != len(names):
            fail("duplicate task names")
        for t in tasks:
            t.compute_ticks(self.tick_ms)
        self.tasks = tasks
        self._assign_priorities()
        by_name = {t.name: t for t in tasks}

        # ---- alarms: one per periodic task, fastest first --------------
        self.periodic = sorted((t for t in tasks if t.period_ms is not None),
                               key=lambda t: t.period_ms)
        for t in self.periodic:
            if (t.period_ms % self.tick_ms) != 0:
                fail(f"task {t.name}: period {t.period_ms} ms is not a "
                     f"multiple of the {self.tick_ms} ms tick")
            if t.period_ticks > self.alarm_max_offset:
                fail(f"task {t.name}: period exceeds the "
                     f"{self.alarm_max_offset}-tick alarm range")
        if not self.periodic:
            fail("at least one periodic task required (kernel needs >= 1 alarm)")

        # ---- resources -------------------------------------------------
        self.resources = [Resource(r, by_name)
                          for r in doc.get("resources", [])]
        rnames = [r.name for r in self.resources]
        if len(set(rnames)) != len(rnames):
            fail("duplicate resource names")
        if not self.resources:
            fail("at least one resource required (kernel config table "
                 "cannot be empty); declare one for your main IPC/shared "
                 "section even if unused")
        if len(self.resources) > 8:
            fail("max 8 resources (held-mask is 8-bit)")

        # ---- pool ------------------------------------------------------
        pool = doc.get("pool", {"block_size": 8, "blocks": 4})
        check_keys(pool, "pool", "pool")
        self.pool_block = int(pool.get("block_size", 8))
        self.pool_blocks = int(pool.get("blocks", 4))
        if not 1 <= self.pool_blocks <= 8:
            fail("pool blocks must be 1..8 (8-bit allocation mask)")
        if self.pool_block < 1:
            fail("pool block_size must be >= 1 (free-list link byte)")

        # ---- peripherals ------------------------------------------------
        self.peripherals = doc.get("peripherals", {}) or {}
        for p in self.peripherals:
            if p not in KNOWN_PERIPHERALS:
                hint = difflib.get_close_matches(str(p),
                                                 KNOWN_PERIPHERALS, n=1)
                extra = (f" (did you mean '{hint[0]}'?)" if hint else
                         f" (known: {', '.join(sorted(KNOWN_PERIPHERALS))})")
                fail(f"unknown peripheral '{p}'{extra}")
        for a, b, why in CONFLICTS_HARD:
            if a in self.peripherals and b in self.peripherals:
                fail(f"peripheral conflict: {a} + {b} - {why}")

        uart = self.peripherals.get("uart") or {}
        if "uart" in self.peripherals:
            check_keys(uart, "uart", "peripherals.uart")
            for ring in ("tx_ring", "rx_ring"):
                v = int(uart.get(ring, 128 if ring == "tx_ring" else 64))
                if not (is_pow2(v) and 2 <= v <= 256):
                    fail(f"uart {ring} must be a power of two, 2..256")

        # ---- gpio + pin ownership matrix --------------------------------
        self.gpio = self._parse_gpio(doc.get("gpio", []) or [])
        self._check_pins()

        # ---- sources / simulink ------------------------------------------
        self.sources = list(doc.get("sources", ["main.c"]))
        self.simulink = doc.get("simulink")
        if self.simulink is not None:
            check_keys(self.simulink, "simulink", "simulink")
            if "model" not in self.simulink:
                fail("simulink section needs a 'model' name")

        # ---- schedulability gate (codegen/README.md par.4) ---------------
        base = self.periodic[0].period_ticks
        load = sum(t.wcet_ticks for t in self.periodic)
        if load > base:
            fail(f"not schedulable: sum of periodic WCETs ({load} ticks) "
                 f"exceeds the base period ({base} ticks); shorten WCETs, "
                 "slow a rate, or merge runnables")
        # harmonic-rate warning (keeps shared release points aligned)
        for slow in self.periodic[1:]:
            if (slow.period_ticks % base) != 0:
                self.warnings.append(
                    f"task {slow.name}: period is not a multiple of the "
                    f"base period - release points drift apart")

    def _parse_gpio(self, entries):
        """Parse the gpio: list into normalized pin records."""
        out = []
        seen = set()
        for e in entries:
            check_keys(e, "gpio", "gpio entry")
            if "pin" not in e:
                fail("gpio entry: needs a 'pin'")
            pin = normalize_pin(e["pin"])
            if pin in seen:
                fail(f"gpio: pin {pin} declared twice")
            seen.add(pin)
            direction = str(e.get("dir", "out")).lower()
            if direction not in ("in", "out"):
                fail(f"gpio {pin}: dir must be 'in' or 'out'")
            out.append({
                "pin": pin,
                "dir": direction,
                "pullup": bool(e.get("pullup", False)),
                "name": e.get("name"),
                "init": int(bool(e.get("init", False))),  # initial out level
            })
        return out

    def _check_pins(self):
        """Build a pin -> owner map across peripherals and gpio; any pin
        claimed twice is a hard error (this subsumes most pair rules)."""
        owner = {}

        def claim(pin, who):
            if pin in owner:
                fail(f"pin conflict on {pin}: '{owner[pin]}' and '{who}' "
                     "both claim it")
            owner[pin] = who

        for p in self.peripherals:
            for pin in PERIPHERAL_PINS.get(p, []):
                claim(pin, f"peripheral {p}")
            # ADC channels are only claimed if the app lists them.
            if p == "adc":
                cfg = self.peripherals.get("adc") or {}
                for ch in cfg.get("channels", []) or []:
                    if 0 <= int(ch) <= 5:  # A6/A7 have no port pin
                        claim(f"PC{int(ch)}", "peripheral adc")
            # acomp with an external positive input also claims AIN0/PD6.
            if p == "acomp":
                cfg = self.peripherals.get("acomp") or {}
                if str(cfg.get("positive", "bandgap")).lower() == "ain0":
                    claim("PD6", "peripheral acomp (AIN0)")
        for g in self.gpio:
            claim(g["pin"], f"gpio {g['name'] or g['pin']}")

    def _assign_priorities(self):
        """Autostart init lowest, then aperiodic in listed order, then
        periodic rate-monotonically (fastest = highest)."""
        auto = [t for t in self.tasks if t.autostart]
        aper = [t for t in self.tasks
                if not t.autostart and t.period_ms is None]
        peri = sorted((t for t in self.tasks if t.period_ms is not None),
                      key=lambda t: -t.period_ms)  # slowest first
        prio = 0
        for t in auto + aper + peri:
            t.priority = prio
            prio += 1

    # ordered helpers -----------------------------------------------------
    @property
    def tasks_by_prio(self):
        return sorted(self.tasks, key=lambda t: t.priority)

    @property
    def alive_tasks(self):
        return sorted((t for t in self.tasks if t.watchdog),
                      key=lambda t: -t.priority)


# ---------------------------------------------------------------------
# Emitters
# ---------------------------------------------------------------------

def emit_config_h(s):
    L = []
    L.append("/**")
    L.append(" * @file    config.h")
    L.append(f" * @brief   {GENERATED_BANNER.format(src=s.src.name)}")
    L.append(" *")
    L.append(" * EROS static application configuration (OSEK \"OIL\" "
             "equivalent).")
    L.append(" * Edit " + s.src.name + " and regenerate; see tools/erosgen.py.")
    L.append(" */")
    L.append("")
    L.append("#ifndef EROS_CONFIG_H")
    L.append("#define EROS_CONFIG_H")
    L.append("")
    L.append('#include "eros_types.h"')
    L.append("")
    L.append("/* ---- system counter --------------------------------------------- */")
    L.append(f"#define OS_TICK_HZ            {s.tick_hz}u")
    L.append(f"#define OS_TICK_MS            {s.tick_ms}u")
    L.append(f"#define OS_ALARM_MAX_OFFSET   {s.alarm_max_offset}u")
    L.append("")
    L.append("/* ---- tasks: TaskID == priority == ready-mask bit ----------------- */")
    L.append("/* WCET budgets (ticks, monitored at +/-1 tick):                      */")
    for t in s.tasks_by_prio:
        per = f"{t.period_ms} ms" if t.period_ms else \
              ("autostart, one-shot" if t.autostart else "activated/chained")
        L.append(f"/*   TASK_{t.name:<10} prio {t.priority}  wcet <= "
                 f"{t.wcet_ticks} tick(s)  ({per}) */")
    L.append(f"#define OS_NUM_TASKS          {len(s.tasks)}u")
    L.append("")
    for t in s.tasks_by_prio:
        L.append(f"#define TASK_{t.name:<16} ((TaskType){t.priority}u)")
    L.append("")
    for t in s.tasks_by_prio:
        L.append(f"extern void {t.entry}(void);")
    L.append("")
    L.append("/* ---- alarms: one cyclic alarm per periodic task ------------------ */")
    L.append(f"#define OS_NUM_ALARMS         {len(s.periodic)}u")
    L.append("")
    for i, t in enumerate(s.periodic):
        L.append(f"#define ALARM_{t.name:<15} ((AlarmType){i}u) "
                 f"/* {t.period_ms} ms -> TASK_{t.name} */")
    L.append("")
    L.append("/* Period macros for SetRelAlarm/SetAbsAlarm calls in the app. */")
    for t in s.periodic:
        L.append(f"#define TASK_{t.name}_PERIOD_TICKS {t.period_ticks}u")
    L.append("")
    L.append("/* ---- resources (IPCP; ceiling = highest-priority user) ---------- */")
    L.append(f"#define OS_NUM_RESOURCES      {len(s.resources)}u")
    L.append("")
    for i, r in enumerate(s.resources):
        users = ", ".join(t.name for t in r.users)
        L.append(f"#define RES_{r.name:<17} ((ResourceType){i}u) "
                 f"/* users: {users} */")
    L.append("")
    L.append("/* ---- fixed-block pool -------------------------------------------- */")
    L.append(f"#define OS_POOL_BLOCK_SIZE    {s.pool_block}u")
    L.append(f"#define OS_POOL_NUM_BLOCKS    {s.pool_blocks}u")
    L.append("")
    L.append("/* ---- watchdog aliveness ------------------------------------------ */")
    if s.alive_tasks:
        parts = " | ".join(f"(1u << TASK_{t.name})" for t in s.alive_tasks)
        L.append("#define OS_ALIVE_REQUIRED_MASK \\")
        L.append(f"    ((uint8_t)({parts}))")
    else:
        L.append("#define OS_ALIVE_REQUIRED_MASK ((uint8_t)0u)")
    L.append("")
    L.append("/* ---- hooks -------------------------------------------------------- */")
    L.append(f"#define OS_CFG_STARTUPHOOK    {s.hook_startup}")
    L.append(f"#define OS_CFG_ERRORHOOK      {s.hook_error}")
    L.append(f"#define OS_CFG_SHUTDOWNHOOK   {s.hook_shutdown}")
    L.append("")
    L.append("/* ---- stack monitoring --------------------------------------------- */")
    L.append(f"#define OS_STACK_CANARY        0x{s.stack_canary:02X}u")
    L.append(f"#define OS_STACK_GUARD_BYTES   {s.stack_guard}u")
    L.append(f"#define OS_STACK_PAINT_MARGIN  {s.stack_margin}u")
    L.append("")
    L.append("/* ---- compile-time validation -------------------------------------- */")
    L.append('OS_STATIC_ASSERT(OS_NUM_TASKS >= 1u, "at least one task required");')
    L.append('OS_STATIC_ASSERT(OS_NUM_TASKS <= 8u, "ready queue is an 8-bit mask: max 8 tasks");')
    L.append("")
    ors = " | ".join(f"(1u << TASK_{t.name})" for t in s.tasks_by_prio)
    L.append("OS_STATIC_ASSERT(")
    L.append(f"    ({ors}) ==")
    L.append("    ((1u << OS_NUM_TASKS) - 1u),")
    L.append('    "task IDs/priorities must be unique bit positions 0..OS_NUM_TASKS-1");')
    L.append("")
    L.append('OS_STATIC_ASSERT(OS_NUM_ALARMS >= 1u, "at least one alarm required");')
    checks = " && ".join(f"(ALARM_{t.name} < OS_NUM_ALARMS)" for t in s.periodic)
    L.append(f"OS_STATIC_ASSERT({checks},")
    L.append('                 "alarm ID out of range");')
    L.append("")
    L.append('OS_STATIC_ASSERT(OS_NUM_RESOURCES <= 8u, "resource held-mask is 8-bit");')
    rchecks = " && ".join(f"(RES_{r.name} < OS_NUM_RESOURCES)" for r in s.resources)
    L.append(f"OS_STATIC_ASSERT({rchecks},")
    L.append('                 "resource ID out of range");')
    L.append("")
    L.append('OS_STATIC_ASSERT((OS_POOL_NUM_BLOCKS >= 1u) && (OS_POOL_NUM_BLOCKS <= 8u),')
    L.append('                 "pool allocation bitmask is 8-bit: 1..8 blocks");')
    L.append('OS_STATIC_ASSERT(OS_POOL_BLOCK_SIZE >= 1u,')
    L.append('                 "free-list link needs one byte per block");')
    L.append("")
    L.append('OS_STATIC_ASSERT((OS_ALIVE_REQUIRED_MASK & ~((1u << OS_NUM_TASKS) - 1u)) == 0u,')
    L.append('                 "aliveness mask references a non-existent task");')
    L.append("")
    L.append("#endif /* EROS_CONFIG_H */")
    return "\n".join(L) + "\n"


def emit_config_c(s):
    L = []
    L.append("/**")
    L.append(" * @file    config.c")
    L.append(f" * @brief   {GENERATED_BANNER.format(src=s.src.name)}")
    L.append(" *")
    L.append(" * Const configuration tables in PROGMEM; the pool arena is the")
    L.append(" * only RAM contributed here (user payload, reported separately")
    L.append(" * from the kernel RAM budget).")
    L.append(" */")
    L.append("")
    L.append("#include <avr/pgmspace.h>")
    L.append("")
    L.append('#include "eros.h"')
    L.append("")
    L.append("const OsTaskConfigType OS_taskConfig[OS_NUM_TASKS] PROGMEM =")
    L.append("{")
    for t in s.tasks_by_prio:
        L.append(f"    [TASK_{t.name}] = {{ {t.entry}, "
                 f"{1 if t.autostart else 0}u /* autostart */, "
                 f"{t.wcet_ticks}u /* WCET ticks */ }},")
    L.append("};")
    L.append("")
    L.append("const OsAlarmConfigType OS_alarmConfig[OS_NUM_ALARMS] PROGMEM =")
    L.append("{")
    for t in s.periodic:
        L.append(f"    [ALARM_{t.name}] = {{ TASK_{t.name} }},")
    L.append("};")
    L.append("")
    L.append("const OsResourceConfigType OS_resourceConfig[OS_NUM_RESOURCES] PROGMEM =")
    L.append("{")
    for r in s.resources:
        L.append(f"    [RES_{r.name}] = {{ TASK_{r.ceiling.name} /* ceiling */, "
                 f"{1 if r.mask_tick_isr else 0}u /* mask tick ISR */ }},")
    L.append("};")
    L.append("")
    L.append("uint8_t OS_poolArena[(uint16_t)OS_POOL_NUM_BLOCKS * OS_POOL_BLOCK_SIZE];")
    return "\n".join(L) + "\n"


def driver_sources(s, app_dir):
    """Resolve peripheral names to source files: app dir wins, then
    drivers_dir (added to VPATH)."""
    local, external = [], []
    for p in sorted(s.peripherals):
        fname = KNOWN_PERIPHERALS[p]
        if (app_dir / fname).exists():
            local.append(fname)
        elif s.drivers_dir and (app_dir / s.drivers_dir / fname).exists():
            external.append(fname)
        else:
            fail(f"peripheral '{p}': source {fname} not found in app dir"
                 + (f" or {s.drivers_dir}" if s.drivers_dir else
                    " (set system.drivers_dir)"))
    return local, external


def periph_defines(s):
    defs = []
    uart = s.peripherals.get("uart")
    if uart is not None:
        uart = uart or {}
        defs.append(f"-DUART_BAUD={int(uart.get('baud', 9600))}UL")
        defs.append(f"-DUART_TX_SIZE={int(uart.get('tx_ring', 128))}u")
        defs.append(f"-DUART_RX_SIZE={int(uart.get('rx_ring', 64))}u")
    return defs


def emit_makefile(s, app_dir):
    local_drv, ext_drv = driver_sources(s, app_dir)
    # Auto-include the generated per-rate ASW files so a fresh project
    # builds without hand-editing sources; dedup against any the user
    # listed explicitly (the reference demos list them for readability).
    asw_files = [f"asw_{t.period_ms}ms.c" for t in s.periodic]
    app_srcs = list(s.sources)
    for f in asw_files + local_drv:
        if f not in app_srcs:
            app_srcs.append(f)
    vpath = [s.kernel_dir]
    if ext_drv:
        vpath.append(s.drivers_dir)
    incs = ["-I.", f"-I{s.kernel_dir}"]
    if ext_drv:
        incs.append(f"-I{s.drivers_dir}")

    model_block = []
    if s.simulink:
        mdir = s.simulink.get("dir", "../codegen")
        model = s.simulink["model"]
        model_block = [
            f"MODEL_DIR  := {mdir}/{model}_ert_rtw",
            "MODEL_SRCS := $(filter-out ert_main.c,"
            "$(notdir $(wildcard $(MODEL_DIR)/*.c)))",
        ]
        vpath.append(f"{mdir} $(MODEL_DIR)")
        incs.append(f"-I{mdir} -I$(MODEL_DIR)")

    defs = periph_defines(s)

    L = []
    L.append("# =====================================================================")
    L.append(f"# {GENERATED_BANNER.format(src=s.src.name)}")
    L.append("#")
    L.append(f"# Application '{s.name}' on the EROS kernel. Only the peripherals")
    L.append("# selected in the YAML are compiled; everything else costs 0 bytes.")
    L.append("# =====================================================================")
    L.append("")
    L.append("MCU     := atmega328p")
    L.append("F_CPU   := 16000000UL")
    L.append(f"TARGET  := {s.name}")
    L.append("")
    L.extend(model_block)
    L.append(f"VPATH   := {' '.join(vpath)}")
    L.append("")
    L.append(f"APP_SRCS := {' '.join(app_srcs)}")
    srcs = "$(APP_SRCS) " + " ".join(ext_drv + ["eros.c", "config.c"])
    if s.simulink:
        srcs += " $(MODEL_SRCS)"
    L.append(f"SRCS     := {srcs}")
    L.append("OBJS     := $(SRCS:.c=.o)")
    L.append("DEPS     := $(SRCS:.c=.d)")
    L.append("")
    L.append("CC      := avr-gcc")
    L.append("OBJCOPY := avr-objcopy")
    L.append("SIZE    := avr-size")
    L.append("AVRDUDE := avrdude")
    L.append("")
    L.append("PORT    ?= /dev/ttyUSB0")
    L.append("BAUD    ?= 57600          # old-bootloader Nano; Optiboot: 115200")
    L.append("")
    if defs:
        L.append("# Peripheral geometry from app.yaml (overrides driver defaults)")
        L.append(f"PERIPH_DEFS := {' '.join(defs)}")
        defs_ref = " $(PERIPH_DEFS)"
    else:
        defs_ref = ""
    L.append("CFLAGS  := -Wall -Wextra -Werror -std=c99 -Os -flto \\")
    L.append("           -ffunction-sections -fdata-sections -fno-common \\")
    L.append(f"           -mmcu=$(MCU) -DF_CPU=$(F_CPU){defs_ref} \\")
    L.append(f"           {' '.join(incs)}")
    L.append("LDFLAGS := -Wl,--gc-sections -Wl,-Map=$(TARGET).map")
    L.append("")
    if s.budget:
        L.append("BUDGET_DIR    := build_budget")
        L.append("CFLAGS_NOLTO  := $(filter-out -flto,$(CFLAGS))")
        L.append(f"FLASH_BUDGET  := {int(s.budget.get('flash', 3072))}")
        L.append(f"RAM_BUDGET    := {int(s.budget.get('ram', 128))}")
        L.append(f"SRAM_TOTAL    := {int(s.budget.get('sram_total', 2048))}")
        L.append("")
        L.append(".PHONY: all size budget flash clean config")
        L.append("")
        L.append("all: $(TARGET).hex size budget")
    else:
        L.append(".PHONY: all size flash clean config")
        L.append("")
        L.append("all: $(TARGET).hex size")
    L.append("")
    L.append("$(TARGET).elf: $(OBJS)")
    L.append("\t$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^")
    L.append("")
    L.append("$(TARGET).hex: $(TARGET).elf")
    L.append("\t$(OBJCOPY) -O ihex -R .eeprom $< $@")
    L.append("")
    L.append("%.o: %.c")
    L.append("\t$(CC) $(CFLAGS) -MMD -MP -c -o $@ $<")
    L.append("")
    L.append("size: $(TARGET).elf")
    L.append('\t@echo "---- final image (LTO) --------------------------------------"')
    L.append("\t@$(SIZE) -B $(TARGET).elf")
    L.append("")
    if s.budget:
        L.append("$(BUDGET_DIR):")
        L.append("\tmkdir -p $(BUDGET_DIR)")
        L.append("")
        L.append("$(BUDGET_DIR)/%.o: %.c | $(BUDGET_DIR)")
        L.append("\t$(CC) $(CFLAGS_NOLTO) -MMD -MP -c -o $@ $<")
        L.append("")
        L.append("APP_BUDGET_OBJS := $(addprefix $(BUDGET_DIR)/,$(APP_SRCS:.c=.o))")
        L.append("")
        L.append("budget: $(BUDGET_DIR)/eros.o $(BUDGET_DIR)/config.o $(APP_BUDGET_OBJS)")
        L.append('\t@echo "---- kernel budget check (non-LTO reference build) ----------"')
        L.append("\t@$(SIZE) -B $(BUDGET_DIR)/eros.o $(BUDGET_DIR)/config.o \\")
        L.append("\t         $(APP_BUDGET_OBJS) | awk ' \\")
        L.append("\t  NR==2 { kflash += $$1 + $$2; kram   = $$2 + $$3 } \\")
        L.append("\t  NR==3 { kflash += $$1 + $$2; arena  = $$2 + $$3 } \\")
        L.append("\t  NR>=4 { appram += $$2 + $$3 } \\")
        L.append("\t  END { \\")
        L.append('\t    printf("kernel Flash (eros.o+config.o) : %4d / %d bytes\\n", \\')
        L.append("\t           kflash, $(FLASH_BUDGET)); \\")
        L.append('\t    printf("kernel static RAM (eros.o)     : %4d / %d bytes\\n", \\')
        L.append("\t           kram, $(RAM_BUDGET)); \\")
        L.append('\t    printf("pool arena (config.o, excluded)   : %4d bytes\\n", arena); \\')
        L.append('\t    printf("application RAM (app objects)     : %4d bytes\\n", appram); \\')
        L.append('\t    printf("stack + idle RAM (of %d total)  : %4d bytes\\n", \\')
        L.append("\t           $(SRAM_TOTAL), $(SRAM_TOTAL) - kram - arena - appram); \\")
        L.append("\t    if (kflash > $(FLASH_BUDGET) || kram > $(RAM_BUDGET)) { \\")
        L.append('\t      printf("BUDGET EXCEEDED\\n"); exit 1; \\')
        L.append("\t    } else { \\")
        L.append('\t      printf("budgets OK\\n"); \\')
        L.append("\t    } \\")
        L.append("\t  }'")
        L.append("")
    L.append("flash: $(TARGET).hex")
    L.append("\t$(AVRDUDE) -v -p m328p -c arduino -P $(PORT) -b $(BAUD) \\")
    L.append("\t           -U flash:w:$(TARGET).hex:i")
    L.append("")
    erosgen_rel = os.path.relpath(os.path.abspath(__file__), str(app_dir))
    L.append("# Regenerate config.h/config.c/Makefile/os_gen.h from the YAML.")
    L.append("# Run this after editing app.yaml (config is NOT auto-rebuilt,")
    L.append("# so a Python-less CI can still 'make' from committed output).")
    L.append("config:")
    L.append(f"\tpython3 {erosgen_rel} {s.src.name}")
    L.append("")
    L.append("clean:")
    if s.budget:
        L.append("\trm -rf $(OBJS) $(DEPS) $(BUDGET_DIR) \\")
        L.append("\t       $(TARGET).elf $(TARGET).hex $(TARGET).map")
    else:
        L.append("\trm -f $(OBJS) $(DEPS) $(TARGET).elf $(TARGET).hex $(TARGET).map")
    L.append("")
    L.append("-include $(DEPS)")
    if s.budget:
        L.append("-include $(addprefix $(BUDGET_DIR)/,$(DEPS))")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------------
# Skeletons (generated once - never overwritten)
# ---------------------------------------------------------------------

def emit_asw_skeleton(s, task):
    step_call = None
    if s.simulink:
        for step, tname in (s.simulink.get("rate_map") or {}).items():
            if str(tname).upper() == task.name:
                step_call = f"{s.simulink['model']}_{step}();"
    L = []
    L.append("/**")
    L.append(f" * @file    asw_{task.period_ms}ms.c")
    L.append(f" * @brief   {task.period_ms} ms rate - TASK_{task.name}.")
    L.append(" *")
    L.append(" * Generated once by tools/erosgen.py - edit freely; it will not")
    L.append(" * be overwritten. Keep rate-local state static in this file;")
    L.append(" * cross-rate signals belong in an asw_signals module.")
    L.append(" */")
    L.append("")
    L.append('#include "eros.h"')
    if s.simulink:
        L.append(f'#include "{s.simulink["model"]}.h"')
    L.append("")
    if task.runnables:
        L.append("/* Runnables you implement (here or in another TU). Move")
        L.append(" * these prototypes to a shared header if reused. */")
        for r in task.runnables:
            L.append(f"extern void {r}(void);")
        L.append("")
    L.append(f"/** TASK_{task.name} - {task.period_ms} ms, WCET <= "
             f"{task.wcet_ticks} tick(s). */")
    L.append(f"void {task.entry}(void)")
    L.append("{")
    if step_call:
        L.append("    /* sample: hardware -> model inports here */")
        L.append(f"    {step_call}")
        L.append("    /* actuate: model outports -> hardware here */")
    for r in task.runnables:
        L.append(f"    {r}();")
    if not step_call and not task.runnables:
        L.append("    /* TODO: runnables for this rate */")
    L.append("    TerminateTask();")
    L.append("}")
    return "\n".join(L) + "\n"


# Driver name -> Init() call emitted into Board_ConfigurePins().
DRIVER_INIT = {
    "uart":       "UART_Init();",
    "pwm":        "PWM_Init();",
    "adc":        "ADC_Init();",
    "i2c":        "I2C_Init();",
    "spi":        "SPI_Init(SPI_MODE0, SPI_CLK_DIV16);",
    "timer0_pwm": "T0PWM_Init();",
    "icp":        "ICP_Init();",
    # eeprom needs no init; extint/acomp are enabled with app-specific
    # arguments, so they are left to hand-written setup.
}
DRIVER_HEADER = {
    "uart": "uart.h", "pwm": "pwm.h", "adc": "adc.h", "eeprom": "eeprom.h",
    "i2c": "i2c.h", "spi": "spi.h", "extint": "extint.h",
    "timer0_pwm": "timer0_pwm.h", "icp": "icp.h", "acomp": "acomp.h",
}


def emit_os_gen_h(s):
    """Always-regenerated glue kept in lockstep with the YAML: board pin
    setup (from gpio + peripheral inits) and alarm arming. main.c calls
    these so adding a task/pin in the YAML propagates without editing
    hand-written code (the regeneration-drift fix)."""
    L = []
    L.append("/**")
    L.append(" * @file    os_gen.h")
    L.append(f" * @brief   {GENERATED_BANNER.format(src=s.src.name)}")
    L.append(" *")
    L.append(" * Regenerated on every erosgen run - never edit. Include it")
    L.append(" * from main.c and call Board_ConfigurePins() in StartupHook()")
    L.append(" * and OS_StartAlarms() in the autostart task, so pin and alarm")
    L.append(" * wiring stay in sync with the YAML.")
    L.append(" */")
    L.append("")
    L.append("#ifndef OS_GEN_H")
    L.append("#define OS_GEN_H")
    L.append("")
    L.append("#include <avr/io.h>")
    L.append('#include "eros.h"')
    for p in sorted(s.peripherals):
        L.append(f'#include "{DRIVER_HEADER[p]}"')
    L.append("")
    L.append("/** Pin directions/pull-ups + enabled-driver init. Call from")
    L.append(" *  StartupHook() (interrupts still disabled). */")
    L.append("static inline void Board_ConfigurePins(void)")
    L.append("{")
    # GPIO directions grouped by port for compactness.
    for g in s.gpio:
        port = g["pin"][1]      # B/C/D
        bit = g["pin"]          # e.g. PB5 - avr-libc defines the bit index
        if g["dir"] == "out":
            L.append(f"    DDR{port} |= (uint8_t)(1u << {bit});"
                     f"  /* {g['name'] or g['pin']} output */")
            if g["init"]:
                L.append(f"    PORT{port} |= (uint8_t)(1u << {bit});")
            else:
                L.append(f"    PORT{port} &= (uint8_t)~(1u << {bit});")
        else:
            L.append(f"    DDR{port} &= (uint8_t)~(1u << {bit});"
                     f"  /* {g['name'] or g['pin']} input */")
            if g["pullup"]:
                L.append(f"    PORT{port} |= (uint8_t)(1u << {bit});"
                         "  /* pull-up */")
    for p in sorted(s.peripherals):
        if p in DRIVER_INIT:
            L.append(f"    {DRIVER_INIT[p]}")
    if not s.gpio and not any(p in DRIVER_INIT for p in s.peripherals):
        L.append("    /* no gpio or auto-init drivers configured */")
    L.append("}")
    L.append("")
    L.append("/** Arm every cyclic alarm with ALIGNED releases (all first")
    L.append(" *  expiries at the base period so shared release points")
    L.append(" *  coincide). Call from the autostart task. */")
    L.append("static inline void OS_StartAlarms(void)")
    L.append("{")
    base = s.periodic[0].period_ticks
    for t in s.periodic:
        L.append(f"    (void)SetRelAlarm(ALARM_{t.name}, {base}u, "
                 f"TASK_{t.name}_PERIOD_TICKS);")
    L.append("}")
    L.append("")
    L.append("#endif /* OS_GEN_H */")
    return "\n".join(L) + "\n"


def emit_main_skeleton(s):
    init = next((t for t in s.tasks if t.autostart), None)
    L = []
    L.append("/**")
    L.append(" * @file    main.c")
    L.append(" * @brief   Integration layer: hooks + init task + main().")
    L.append(" *")
    L.append(" * Generated once by tools/erosgen.py - edit freely. Pin setup")
    L.append(" * and alarm arming live in os_gen.h (regenerated every run).")
    L.append(" */")
    L.append("")
    L.append('#include "eros.h"')
    L.append('#include "os_gen.h"')
    L.append("")
    if s.hook_startup:
        L.append("void StartupHook(void)")
        L.append("{")
        L.append("    Board_ConfigurePins(); /* generated: gpio + driver init */")
        L.append("}")
        L.append("")
    if s.hook_error:
        L.append("void ErrorHook(StatusType error)")
        L.append("{")
        L.append("    (void)error; /* may run in tick-ISR context: stay tiny */")
        L.append("}")
        L.append("")
    if s.hook_shutdown:
        L.append("void ShutdownHook(StatusType error)")
        L.append("{")
        L.append("    (void)error; /* terminal fault tombstone */")
        L.append("}")
        L.append("")
    if init is not None:
        L.append(f"/** TASK_{init.name} - autostart: arm the cyclic alarms. */")
        L.append(f"void {init.entry}(void)")
        L.append("{")
        if s.simulink:
            L.append(f"    {s.simulink['model']}_initialize();")
        L.append("    OS_StartAlarms(); /* generated from the YAML task set */")
        L.append("    TerminateTask();")
        L.append("}")
        L.append("")
    L.append("int main(void)")
    L.append("{")
    L.append("    StartOS(); /* noreturn */")
    L.append("}")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------

def report(s):
    print(f"erosgen: system '{s.name}' ({s.src})")
    print(f"  tick: {s.tick_hz} Hz")
    print("  tasks (prio high->low):")
    for t in reversed(s.tasks_by_prio):
        kind = (f"{t.period_ms} ms" if t.period_ms else
                ("autostart" if t.autostart else "activated"))
        wd = " wdg" if t.watchdog else ""
        print(f"    {t.priority}  TASK_{t.name:<10} {kind:>10}  "
              f"wcet {t.wcet_ticks} tick(s){wd}  -> {t.entry}()")
    base = s.periodic[0]
    load = sum(t.wcet_ticks for t in s.periodic)
    print(f"  schedulability: sum(WCET)={load} ticks <= base period "
          f"{base.period_ticks} ticks  OK")
    print("  static RAM plan:")
    arena = s.pool_block * s.pool_blocks
    print(f"    kernel state          ~35 B")
    print(f"    pool arena            {arena} B "
          f"({s.pool_blocks} x {s.pool_block})")
    uart = s.peripherals.get("uart")
    if uart is not None:
        uart = uart or {}
        tx, rx = int(uart.get("tx_ring", 128)), int(uart.get("rx_ring", 64))
        print(f"    uart rings            {tx + rx} B (TX {tx} + RX {rx})")
    for w in s.warnings:
        print(f"  WARNING: {w}")


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def write(path, content, check_only, overwrite=True):
    if not overwrite and path.exists():
        return "kept"
    if check_only:
        return "would write"
    path.write_text(content)
    return "wrote"


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("--")]
    check_only = "--check" in argv
    if len(args) != 1:
        print(__doc__)
        return 2
    src = Path(args[0]).resolve()
    if not src.exists():
        print(f"erosgen: {src} not found")
        return 2
    app_dir = src.parent

    try:
        doc = yaml.safe_load(src.read_text())
        s = System(doc, src)
        outputs = [
            (app_dir / "config.h", emit_config_h(s), True),
            (app_dir / "config.c", emit_config_c(s), True),
            (app_dir / "Makefile", emit_makefile(s, app_dir), True),
            (app_dir / "main.c", emit_main_skeleton(s), False),
        ]
        # os_gen.h (pin + alarm glue) is refreshed only for apps that use
        # it: a freshly generated main.c includes it, and any main.c that
        # references it keeps getting refreshed. Hand-written mains that
        # manage their own startup (the reference demos) are left alone.
        main_path = app_dir / "main.c"
        uses_os_gen = (not main_path.exists()) or \
            ("os_gen.h" in main_path.read_text())
        if uses_os_gen:
            outputs.append((app_dir / "os_gen.h", emit_os_gen_h(s), True))
        for t in s.periodic:
            fname = app_dir / f"asw_{t.period_ms}ms.c"
            outputs.append((fname, emit_asw_skeleton(s, t), False))
    except ConfigError as e:
        print(e)
        return 1

    report(s)
    for path, content, overwrite in outputs:
        action = write(path, content, check_only, overwrite)
        print(f"  {action}: {path.relative_to(app_dir)}")
    missing = [f for f in s.sources if not (app_dir / f).exists()]
    for f in missing:
        print(f"  WARNING: listed source {f} does not exist (yet)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
