/**
 * @file    Rte_motor.h
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * Contract-phase application header for the 'motor' SWC: its RTE
 * run entry + the ports it binds. Include this alone to compile the
 * SWC's integration before the full system Rte.h is configured.
 */

#ifndef RTE_MOTOR_H
#define RTE_MOTOR_H

/* Input ports (BSW sensor / producer SWC -> ASW): */
/*   IN_Speed_Rpm (uint16_T) <- adc */
/* Output ports (ASW -> BSW actuator): */
/*   OUT_Fan_B (boolean_T) -> dio */

/** One activation of this SWC: read inputs -> run -> write outputs. */
void Rte_Run_motor(void);

#endif /* RTE_MOTOR_H */
