/**
 * @file    Rte_Cfg.h
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * Declarative ASW<->BSW binding for 2 SWCs ('appKnbSwt', 'motor'):
 * which driver feeds each input port, which each output port
 * actuates, and each runnable rate. Pure configuration, no logic.
 */

#ifndef RTE_CFG_H
#define RTE_CFG_H

/* ================= SWC: appKnbSwt ================= */
/* ---- SWC identity (ASW entry points) ---------------------------- */
#define RTE_CFG_APPKNBSWT_INIT_FN  appKnbSwt_initialize
#define RTE_CFG_APPKNBSWT_RUNNABLE_FN appKnbSwt_Runnable

/* ---- Input ports: BSW sensor -> ASW port ------------------------ */
/* IN_KnbVal_Z (uint16_T) <- adc */
#define RTE_CFG_KNBVAL_Z_SIGNAL    IN_KnbVal_Z
#define RTE_CFG_KNBVAL_Z_ADC_CH    0u

/* ---- Output ports: ASW port -> BSW actuator --------------------- */
/* OUT_Led1_B (boolean_T) -> dio */
#define RTE_CFG_LED1_B_SIGNAL      OUT_Led1_B
#define RTE_CFG_LED1_B_DDR         DDRB
#define RTE_CFG_LED1_B_PORT        PORTB
#define RTE_CFG_LED1_B_BIT         5u

/* ---- Scheduling: runnable rate assigned to the OS -------------- */
#define RTE_CFG_APPKNBSWT_PERIOD_MS 10u

/* ================= SWC: motor ================= */
/* ---- SWC identity (ASW entry points) ---------------------------- */
#define RTE_CFG_MOTOR_INIT_FN      motor_initialize
#define RTE_CFG_MOTOR_RUNNABLE_FN  motor_Runnable

/* ---- Input ports: BSW sensor -> ASW port ------------------------ */
/* IN_Speed_Rpm (uint16_T) <- adc */
#define RTE_CFG_SPEED_RPM_SIGNAL   IN_Speed_Rpm
#define RTE_CFG_SPEED_RPM_ADC_CH   1u

/* ---- Output ports: ASW port -> BSW actuator --------------------- */
/* OUT_Fan_B (boolean_T) -> dio */
#define RTE_CFG_FAN_B_SIGNAL       OUT_Fan_B
#define RTE_CFG_FAN_B_DDR          DDRC
#define RTE_CFG_FAN_B_PORT         PORTC
#define RTE_CFG_FAN_B_BIT          0u

/* ---- Scheduling: runnable rate assigned to the OS -------------- */
#define RTE_CFG_MOTOR_PERIOD_MS    20u

#endif /* RTE_CFG_H */
