/**
 * @file    Rte.h
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * RTE public API for the 'appKnbSwt' model<->OS integration.
 */

#ifndef RTE_H
#define RTE_H

/** BSW init for the bound ports + ASW init. Call once, with
 *  interrupts disabled (StartupHook via os_gen.h). */
void Rte_Init(void);

/** One activation: read input ports <- BSW, run the runnable,
 *  write output ports -> BSW. */
void Rte_Run_appKnbSwt(void);

#endif /* RTE_H */
