/**
 * @file    Rte_appKnbSwt.h
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * Contract-phase application header for the 'appKnbSwt' SWC: its RTE
 * run entry + the ports it binds. Include this alone to compile the
 * SWC's integration before the full system Rte.h is configured.
 */

#ifndef RTE_APPKNBSWT_H
#define RTE_APPKNBSWT_H

/* Input ports (BSW sensor / producer SWC -> ASW): */
/*   IN_KnbVal_Z (uint16_T) <- adc */
/* Output ports (ASW -> BSW actuator): */
/*   OUT_Led1_B (boolean_T) -> dio */

/** One activation of this SWC: read inputs -> run -> write outputs. */
void Rte_Run_appKnbSwt(void);

#endif /* RTE_APPKNBSWT_H */
